---
title: "Definitions of DD instruments"
output: html_document
---
<br/>

#### Agenda Initiative
An instrument that allows a certain number of citizens to put an issue on the agenda of state organs but that does not lead to a referendum (i.e. a popular vote). An agenda initiave mandates the state organ to deal with the proposal: make a decision about it or at least debate it.

#### Proactive citizens’ initiative
An instrument that allows a certain number of citizens to initiate a referendum and formulate the topic of the referendum.

#### Rejective citizens’ initiative
An instrument that allows a certain number of citizens to initiate a referendum that is aimed at preventing new laws (or parts of them) from being passed or at repealing existing laws (or parts of them).

#### Law-initiated referendum
A referendum that is triggered if certain conditions specified by law (i.e. the constitution or a legislative act) are met. The law may determine the topic (e.g. transfer of sovereignty) or the type of legal act (e.g. constitutional amendment) that triggers the referendum process. The law can either directly require the holding of a referendum or require it in case certain additional conditions are not met (e.g. a constitutional amendment is not passed by a supermajority in parliament). In all cases the referendum is triggered by law rather than initiated by a state organ.

#### Legislature-initiated referendum
A referendum that can be initiated by the legislature (i.e. parliament (or parts of it)). A referendum is initiated by the legislature if the parliament or members of the parliament can start the referendum process by defining the issue for the popular vote. The fact that another state organ may be responsible for calling the referendum (i.e. for making the final decision about it) does not matter. The deciding question is who starts the process.

#### Subnational-initiated referendum
A referendum that can be initiated by (a certain number of) subnational entities (regions, provinces, cantons; municipalities). A referendum is initiated by a subnational entity if it can start the referendum process by defining the issue for the popular vote.

#### Executive-initiated referendum
A referendum that can be initiated by the executive (i.e. the government (or parts of it)). A referendum is initiated by the executive if the government or other executive actors can start the referendum process by defining the issue for the popular vote. The fact that another state organ may be responsible for calling the referendum (i.e. for making the final decision about it) does not matter. The deciding question is who starts the process.


